# Site
repository: xuxin/resume
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Xin Xu
title: Computer Science and Technology (Intelligent Science and Technology)
email: xuxinpkucs@gmail.com
# email_title: Email (Email title override)
phone: (+86) 13407228245
# phone_title: Phone (Phone title override)
# website: https://xuxinthuad.github.io/
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: xuxinthu
github_username:  JACK-Shinn
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: xuxinthu
# flickr_username: jekyll
# instagram_username: xuxinthu
# linkedin_username: david-xu-1a298828b
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: xuxinthu
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: sPcjwrIAAAAJ

# Additional icon links
# additional_links:
# - title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/xuxin_me.jpg
about_content: | 
  Ph.D. in Artificial Intelligence, School of Intelligence Science and Technology, Peking University (2020–2025), specializing in large language models (LLMs) and sequence modeling, where I pioneered architectures for efficient long-context reasoning, Advised by Prof. Zhouchen Lin (IEEE Fellow). Previously, as an M.S. candidate at Tsinghua University, and hold a B.Eng. in Automatic Control (Shandong University, Top 1%). My work bridges theoretical innovation (state-space models, hybrid expert systems) with LLM.

content:
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Xiaopeng - Autonomous Driving Center, Shanghai
        sub_title: Senior Algorithm Engineer
        caption: September 2022 – Present
        link: https://www.xiaopeng.com/about.html
        quote: > 
          
        description: | # this will include new lines to allow paragraphs
          (1) Responsible for Xiaopeng P5 mass production model prediction module (CNGP)
          
            - Delivered high-priority issues in OTA4, reducing the rate of false deceleration by over 20% and decreasing the takeover rate by over 30%.
            
            - Enriched a simulation test dataset with over 3000 different scenarios, including intersections, roundabouts, and merge scenarios.

          (2) Responsible for Xiaopeng G9 mass production model prediction module (CNGP, HNGP 2.0)

            - Achieved safety takeovers close to 1 per thousand kilometers for HNGP 2.0 and reduced false decelerations to nearly 4 per thousand kilometers.
    
            - Implemented interactive framework for small intersection prediction algorithms, increasing the vehicle's passing capability at small intersections by over 30%.
    
            - Introduced exit prediction and behavior imitation prediction models, resulting in safety takeovers occurring less than 1 per hundred kilometers.

          (3) Responsible for Xiaopeng G9 mass production model prediction module (XNGP 2.0)

            - Implemented features such as lane optimization at unmarked intersections and merge predictions, achieving a vehicle's passing capability comparable to CNGP at 80%.
    
            - Continuously improved algorithms for scenarios including intersections, roundabouts, small intersections, and cruise control in OTA3, addressing algorithm glitches and ensuring successful deployments in Shanghai and Beijing.
    
            - Completed crucial feature enhancements and algorithm glitch fixes in the XNGP 2.0 sprint plan, resulting in a reduction of takeover rates and false deceleration rates by over 20%.

      - layout: right
        title: JD Group - X Research Department, Beijing
        sub_title: Algorithm Engineer
        caption: August 2020 – August 2022
        link: https://neuhub.jd.com/brand/1
        quote: > 
          
        description: | # this will include new lines to allow paragraphs
          (1) Cutting-Edge Algorithm Research
          
            - Published 11 international top-tier/high-level academic papers during my tenure
            
            - Filed 66 invention patents during my tenure, with 7 patents currently granted
            
            - Served as a reviewer for over ten international top-tier conferences/journals (CVPR 2022, ICML 2022, etc.)

          (2) Responsible for the Prediction Trajectory Prediction Module
          
            - Utilized deep learning methods (LSTM) combined with rules to predict the future movement trajectories of obstacles, resulting in the deployment of the ROVER 5.0 model and a 1.5% improvement in the ADE metric for daily simulation tasks.
            
            - Enhanced efficiency by conducting experiments for over 200 models in a short period, reducing training time from 7 days to 8 hours.
            
            - Combined LSTM networks with VectorNet, further improving the ADE metric by 2%.

            
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Peking University
        sub_title: Ph.D. in Computer Science and Technology (Intelligent Science and Technology)
        caption: 2020 -- 2025
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          Research Focus: Large Language Models (LLMs), Sequence Modeling, State Space Models
    
      - layout: top-right
        title: Tsinghua University
        sub_title: Master's Degree, Instrumentation and Measurement Engineering
        caption: 2017 -- 2020
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          Research Focus: Machine Learning, Deep Learning, Computer Vision

      - layout: top-right
        title: Shandong University
        sub_title: Bachelor's Degree, Measurement and Control Technology and Instruments
        caption: 2013 -- 2017
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          Research Focus: Control Theory and Control Engineering, Robotics
          
  - title: Papers
    layout: text
    content: | # this will include new lines to allow paragraphs
  - Xin Xu, and Zhouchen Lin. "MixCon: A Hybrid Architecture for Efficient and Adaptive Sequence Modeling." European Conference on Artificial Intelligence, 2024. \href{https://github.com/JACK-Shinn/MixCon/blob/main/MixCon.pdf}{[paper]}\href{https://github.com/JACK-Shinn/MixCon/tree/main/MixCon/MixCon}{[code]}\\
  

  - Xin Xu, and Zhouchen Lin. "Vision Conba: An Efficient and Adaptive Vision Sequence Analysis Framework." \href{https://github.com/JACK-Shinn/AAAI25_VisionConba/blob/main/AAAI25_Vision_Conba.pdf}{[paper]}

  - Xin Xu, Yisen wang and Zhouchen Lin. "VideoConba: An Efficient and Adaptive Framework for Video Understanding." \href{https://github.com/JACK-Shinn/CVPR25_VideoConba/blob/main/CVPR25_Video_Conba.pdf}{[paper]}

  - Xin Xu, and Zhouchen Lin. "Learning Nonseparable Sparse Regularizers via Multivariate Activation Functions." \href{https://github.com/JACK-Shinn/MAF_SRL/blob/main/ICML21_MAF_SRL.pdf}{[paper]}\href{https://github.com/JACK-Shinn/MAF_SRL/blob/main/ICML21_MAF_SRL_Appendix.pdf}{[Appendix]}


  - title: 发明专利
    layout: text
    content: | # this will include new lines to allow paragraphs
      - 林宙辰，\textbf{徐鑫}. 基于凸多面体分段线性分类的二叉划分树车牌识别方法. 公开号：CN111598080A.

      - 林宙辰，\textbf{徐鑫}. 基于多元激活函数的稀疏正则化神经网络的图像分类方法. 公开号：CN113313175A.
      

# Footer
footer_show_references: true
references_title: https://jack-shinn.github.io/xuxinpku_resume.github.io/

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
