---
repository: xuxin/resume
version: 2
name: Xin Xu
title: Computer Science and Technology (Intelligent Science and Technology)
email: xuxinpkucs@gmail.com
phone: (+86) 13407228245
darkmode: false
# github_username: JACK-Shinn
about_profile_image: images/xuxin_me.jpg
about_content: >
  Ph.D. candidate in Artificial Intelligence at the School of Intelligence Science and Technology, Peking University (2020–2025), under the supervision of Prof. Zhouchen Lin (IEEE Fellow). Specializing in large language models (LLMs) and sequence modeling, I have pioneered groundbreaking architectures to revolutionize efficient long-context reasoning and spatiotemporal intelligence.
  
  As a trailblazer in adaptive sequence modeling, I developed the MixCon hybrid architecture, integrating control theory-inspired feedback mechanisms with Transformer layers and dynamic MoE routing. This innovation enables single-GPU processing of 128K-token sequences, achieving 1.5× throughput over Jamba and 4.5× over Mixtral on A800 GPUs, while setting new SOTA on HellaSwag (89.3) and WinoGrande (87.6) with 63% reduced memory overhead. My work on Vision Conba (ViC) bridges local visual details and global semantics through a selective bidirectional state model, achieving an 11.9% leap in ImageNet top-1 accuracy (85.4%) and 58.9 box AP on COCO with 30% fewer FLOPs than state-of-the-art baselines.
  
  For video and 4D perception, I designed Video Conba to integrate 3D convolutional dynamics with control-theoretic stability, boosting Kinetics-400 accuracy to 82.1% (2.0% over ViT-L) with 45% less memory. My Conba4D framework further decouples spatiotemporal modeling for efficient 4D point cloud processing, achieving 93.23% accuracy on MSR-Action3D (SOTA) while enabling real-time inference at 58 FPS—5.36× faster than prior art—with 87.5% reduced GPU memory usage.
  
  Holding a B.Eng. in Automatic Control from Shandong University (Top 1%) and prior research at Tsinghua University, my work uniquely merges theoretical advancements in state-space models and hybrid expert systems with practical LLM/vision applications, driving breakthroughs in efficiency, scalability, and multimodal understanding.
content:

  - title: Internship
  layout: list
  content:
    - layout: right
      title: Baidu MEG - Large Model NLP Algorithms
      quote: >
        "Redefining industrial recommendation systems through cascaded representation learning and generative retrieval"
      description: >
        - Core contributor of COBRA framework proposing sparse-dense cascaded representation and RQ-VAE, boosting CVR by 3.6% and ARPU by 4.15%<br>
        - Innovated dynamic sparse ID-guided dense vector refinement mechanism achieving 12.3% NDCG@10 improvement and 9.8% CTR gain over Google TIGER<br>
        - Developed coarse-to-fine generative retrieval pipeline reducing inference latency to 32ms (-41%) with 24k QPS per node (30× throughput increase)

    - layout: right
      title: Baidu TPG - X1 Turbo Development
      quote: >
        "Pioneering closed-loop training-generation framework for industrial-scale LLM optimization"
      description: >
        - Architected MixCon integration into X1 Turbo establishing "Train-Generate-Feedback-Enhance" loop, accelerating CLUE benchmark inference by 37%<br>
        - Achieved 5.4× training throughput and 8× inference speedup over 4.5 Turbo with 40% VRAM reduction<br>
        - Enhanced logical reasoning surpassing DeepSeek R1/V3 through self-feedback augmented MoE training<br>
        - Collaborated cross-team to deploy X1 Turbo with 0.83s latency (-40% vs 4.5 Turbo) and 25% API cost of competitors

  - title: Research Experience
    layout: list
    content:
      - layout: right
        title: MixCon Architecture for Long-Context Modeling
        quote: >
          "Redefining efficiency frontiers in long-sequence processing through
          control-inspired adaptive mechanisms"
        description: >
          - Proposed Conba architecture integrating control theory principles
          (feedback loops, adaptive gain) with sequence modeling, achieving 40%
          faster convergence than Transformer baselines<br>

          - Designed MixCon hybrid architecture combining Conba layers, Transformer blocks, and dynamic MoE routing, enabling 128K-token context processing on single GPUs<br>

          - Implemented hardware-aware kernel optimizations achieving 1.5× throughput over Jamba and 4.5× over Mixtral on A800 GPUs<br>

          - Attained SOTA on HellaSwag (89.3) and WinoGrande (87.6) while reducing memory overhead by 63% through selective state updates
      - layout: right
        title: Vision Conba (ViC) for Multimodal Understanding
        quote: >
          "Bridging local-global visual semantics through biologically inspired
          state propagation"
        description: >
          - Developed SBSM module enabling simultaneous local feature
          preservation and global context aggregation<br>

          - Achieved 85.4% ImageNet top-1 accuracy (11.9% absolute improvement) via adaptive receptive field control<br>

          - Designed shift-equivariant Conba blocks reducing texture bias by 38% compared to standard CNNs<br>

          - Extended to detection/segmentation tasks: ViC-T attained 58.9 box AP on COCO (4.2 gain over Swin-L) with 30% fewer FLOPs
      - layout: right
        title: Video Conba for Spatiotemporal Modeling
        quote: >
          "Temporal reasoning meets control-theoretic stability in video
          architectures"
        description: >
          - Created 3D-Conba blocks combining causal/non-causal temporal
          modeling with spatial SSMs<br>

          - Introduced differential positional encoding adapting to motion magnitudes (3.2% accuracy boost)<br>

          - Achieved 82.1% on Kinetics-400 (2.0% over ViT-L) with 45% less memory consumption<br>

          - Demonstrated 6.1% superiority over ViS4mer in 10-minute video understanding tasks through multiscale state compression
      - layout: right
        title: Conba4D for 4D Perception
        quote: >
          "Spatiotemporal intelligence through decoupled hierarchical state spaces"
        description: >+
          - Developed disentangled spatial-temporal Conba modules enabling
          efficient 4D processing<br>

          - Introduced dynamic kernel adjustment reducing GPU memory by 87.5% in 256-frame sequences<br>

          - Achieved 93.23% on MSR-Action3D (SOTA) via learnable spatiotemporal scanning strategies<br>

          - Enabled real-time 4D perception at 58 FPS (5.36× speedup) while maintaining 94% of offline accuracy

              
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Peking University
        sub_title: Ph.D. in Computer Science and Technology (Intelligent Science and
          Technology)
        caption: 2020 -- 2025
        quote: ""
        description: >
          Research Focus: Large Language Models (LLMs), Sequence Modeling,
          State Space Models
      - layout: top-right
        title: Tsinghua University
        sub_title: Master's Degree, Instrumentation and Measurement Engineering
        caption: 2017 -- 2020
        quote: ""
        description: |
          Research Focus: Machine Learning, Deep Learning, Natural Language Processing
      - layout: top-right
        title: Shandong University
        sub_title: Bachelor's Degree, Measurement and Control Technology and Instruments
        caption: 2013 -- 2017
        quote: ""
        description: |
          Research Focus: Control Theory and Control Engineering, Computer Vision
  - title: Papers
    layout: text
    content: >
      - Xin Xu, Zhouchen Lin. "MixCon: A Hybrid Architecture for Efficient and Adaptive Sequence Modeling." European Conference on Artificial Intelligence, ECAI 2024.

      - Xin Xu, Zhouchen Lin. "Vision Conba: An Efficient and Adaptive Vision Sequence Analysis Framework."

      - Xin Xu, Yisen wang, Zhouchen Lin. "VideoConba: An Efficient and Adaptive Framework for Video Understanding."

      - Xin Xu, Zhouchen Lin. "Learning Nonseparable Sparse Regularizers via Multivariate Activation Functions." 

      - Haiming Wang, Liangliang Zhang, Qi Kong, Weicheng Zhu, Jie Zheng, Li Zhuang and Xin Xu (Corresponding Author). Motion planning in complex urban environments: An industrial application on autonomous last‐mile delivery vehicles. Journal of Field Robotics (JFR), 2022. (Impact Factor: 8.3, Q1)

      - Fan Zhu, Lin Ma, Xin Xu, Dingfeng Guo, Xiao Cui, Qi Kong. Baidu apollo auto-calibration system-an industry-level data-driven and learning based vehicle longitude dynamic calibrating algorithm. arXiv preprint arXiv:1808.10134, 2018.

      - Fan Zhu, Xin Xu, Lin Ma, Dingfeng Guo, Xiao Cui, Qi Kong. Autonomous driving vehicle control auto-calibration system: An industry-level, data-driven and learning-based vehicle longitudinal dynamic calibrating algorithm.
      
      - Qi Kong, Liangliang Zhang, Xin Xu (Corresponding Author). Lane Keeping Algorithm for Autonomous Driving via Safe Reinforcement Learning. International Conference on Knowledge Science, Engineering and Management (KSEM), 2021. 

      - Qi Kong, Xin Xu (co-first author), Liangliang Zhang. ODNASSD: An End-to-end Object Detection Neural Architecture Search Space Design. IEEE International Intelligent Transportation Systems Conference (ITSC), 2021. 

      - Xin Xu, Liangliang Zhang, Qi Kong. Learning Bilevel Sparse Regularized Neural Network. CAAI International Conference on Artificial Intelligence, 2021.

      - Qi Kong, Liangliang Zhang, Xin Xu (Corresponding Author). MITNet: Multi-intention Trajectory Network for Motion Prediction. IEEE International Conference on Image, Vision and Computing (ICIVC), 2021. (Best Paper Award)

      - Xin Xu, Liangliang Zhang, Qi Kong, Chenguang Gui, Xing Zhang. Enhanced-historical average for long-term prediction. IEEE International Conference on Computer, Control and Robotics (ICCCR), 2022.

      - Qi Kong, Liangliang Zhang, Xin Xu (Corresponding Author). Constrained policy optimization algorithm for autonomous driving via reinforcement learning. IEEE International Conference on Image, Vision and Computing (ICIVC), 2021. 

      - Qi Kong, Liangliang Zhang, Xin Xu (Corresponding Author). VPNet: Vision and Planning Network for Robotic Navigation. IEEE International Conference on Image, Vision and Computing (ICIVC), 2021. 

      - Qi Kong, Liangliang Zhang, Xin Xu (Corresponding Author). Control algorithm of path planning and path tracking for automated valet parking. Journal of Physics: Conference Series, 2022. 

      - Qi Kong, Liangliang Zhang, Xin Xu (Corresponding Author). Outdoor real-time RGBD sensor fusion of stereo camera and sparse lidar. Journal of Physics: Conference Series, 2022. 
      
      - Qi Kong, Liangliang Zhang, Xin Xu (Corresponding Author). Vehicle Localization with Surveillance Cameras. IEEE International Conference on Vision, Image and Signal Processing (ICVISP), 2021.
      
      - VPNet: Vision and Planning Network for Robotic Navigation. IEEE International Conference on Image, Vision and Computing (ICIVC), 2021. 

      - Qi Kong, Xin Xu (co-first author), Liangliang Zhang. MEMA-NAS: Memory-Efficient Multi-Agent Neural Architecture Search, PRCV 2021.
    layout: text
    content: |
      已授权专利：

      -CN111598080B，基于凸多面体分段线性分类的二叉划分树车牌识别方法。 

      -CN113313175B，基于多元激活函数的稀疏正则化神经网络的图像分类方法。

      -CN112896191B，轨迹处理方法、装置、电子设备和计算机可读介质
      
      -CN113119996B，一种轨迹预测方法、装置、电子设备及存储介质
      
      -CN113548052B，无人驾驶车辆换道控制方法和装置 
      
      -CN113978548B，应用于无人车的转向协同控制方法、装置、设备及介质
  
      -CN113561972B，一种避障控制方法、装置、车辆和存储介质
  
      -CN114664098B，一种路权分配方法和装置
  
      -CN113031600B，一种轨迹生成方法、装置、存储介质及电子设备
  
      -CN113807351B，一种场景文字检测方法和装置
  
      -CN113838113B，三维物体识别方法和装置
  
      -CN113691606B，任务卸载方法、装置、电子设备、系统和存储介质
  
      -CN113780270B，目标检测方法和装置
  
      -CN114261400B，一种自动驾驶决策方法、装置、设备和存储介质
  
      -CN114212104B，车辆控制方法、装置、车辆和存储介质
  
      -CN113849400B，一种测试场景库生成方法、装置、设备及存储介质
  
      -CN113989757B，辅助驾驶方法、装置、电子设备及存储介质
  
      -CN114889603B，一种车辆换道处理方法和装置
 
      -CN114580539B，一种车辆驾驶策略处理方法和装置
  
      -CN114675655B，一种车辆控制方法及装置

      实质审查中专利：
      
      -CN119625407A，一种基于自适应控制状态空间模型的图像分类方法。

      -CN114581868A，基于模型通道剪枝的图像分析方法和装置

      -CN114998388A，轨迹预测方法和装置

      -CN114842460A，一种场景文字检测的方法和装置

      -CN114549838A，分割点云数据的方法、装置、设备和计算机可读介质

      -CN114445630A，图像分割及模型训练方法、装置、终端设备及存储介质

      -CN114187589A，一种目标检测方法、装置、设备和存储介质

      -CN114187311A，一种图像语义分割方法、装置、设备及存储介质

      -CN113703453A，确定行驶轨迹的方法、装置、电子设备及存储介质

      -CN114936670A，一种交通预测的方法和装置

      -CN114821537A，活动意图预测方法、装置及无人车

      -CN114399107A，一种交通状态感知信息的预测方法及系统

      -CN114386481A，一种车辆感知信息融合方法、装置、设备及存储介质

      -CN114387325A，一种图像特征处理方法和装置

      -CN113947948A，一种车辆通行控制方法和装置

      -CN113808187A，视差图生成方法、装置、电子设备和计算机可读介质

      -CN115272666A，在线点云语义分割方法、装置、存储介质及电子设备

      -CN114371709A，路径规划方法、设备、存储介质及程序产品

      -CN113971727A，一种语义分割模型的训练方法、装置、设备和介质

      -CN114537421A，调整系统故障的方法、装置、设备和计算机可读介质

      -CN114091592A，一种车辆感知信息融合方法、装置、设备及存储介质

      -CN114771570A，自动驾驶车辆的控制方法和装置

      -CN114771555A，自主泊车故障诊断方法、装置和和无人驾驶车辆

      -CN114022663A，目标行为候选框生成方法及装置、电子设备、存储介质

      -CN114663848A，一种基于知识蒸馏的目标检测方法和装置

      -CN114399791A，一种行人检测方法、装置、设备和介质

      -CN113792655A，一种意图识别方法、装置、电子设备及计算机可读介质

      -CN113780148A，交通标志图像识别模型训练方法和交通标志图像识别方法

      -CN114140468A，三维点云的语义确定方法和装置

      -CN114604273A，车辆轨迹规划方法、装置、存储介质及电子设备

      -CN114167874A，信息更新方法、路线筛选方法、装置、设备和介质

      -CN114841276A，数据处理方法和装置、电子设备、计算机可读介质

      -CN114677440A，图像数据处理方法、装置和设备

      -CN114670871A，一种自动驾驶车辆的预测控制方法和装置

      -CN114387197A，一种双目图像处理方法、装置、设备和存储介质

      -CN114359893A，物体检测方法、装置、电子设备和存储介质

      -CN113781540A，网络生成方法、装置、电子设备和计算机可读介质

      -CN114495058A，交通标志检测方法和装置

      -CN114004406A，车辆轨迹预测方法、装置、存储介质及电子设备

      -CN113781539A，深度信息获取方法、装置、电子设备和计算机可读介质

      -CN115130680A，机器学习模型的训练方法、无人车的控制方法和无人车

      -CN114954520A，一种控制无人驾驶车辆的方法和装置

      -CN114834467A，自动驾驶车辆的控制运行方法、装置及无人车

      -CN114021840A，换道策略生成方法和装置、计算机存储介质、电子设备

      -CN114834469A，人机共驾冲突控制方法、装置、存储介质及电子设备

      -CN114735027A，应用于无人车的运行决策方法及装置

      -CN114818498A，匝道汇入策略学习方法、装置、电子设备和存储介质

      -CN114004972A，一种图像语义分割方法、装置、设备和存储介质 
plugins:
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - lib/
  - scripts/
  - docker-compose.yml
