# Site
repository: xuxin/resume
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Xin Xu
title: Senior Algorithm Engineer
email: xuxinthu@gmail.com
# email_title: Email (Email title override)
phone: (+86)  13121058823
# phone_title: Phone (Phone title override)
# website: https://xuxinthuad.github.io/
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: xuxinthu
github_username:  xuxinthu
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: xuxinthu
# flickr_username: jekyll
# instagram_username: xuxinthu
linkedin_username: david-xu-1a298828b
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: xuxinthu
# orcid_username: 0000-0000-0000-0000
googlescholar_username: sPcjwrIAAAAJ

# Additional icon links
# additional_links:
# - title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/xuxin_me.jpg
about_content: | 
  I am currently serving as a Senior Algorithm Engineer at Xiaopeng Autonomous Driving Center, where I have the privilege of contributing significantly to the advancement of autonomous driving technology. My academic journey includes obtaining a Master's degree from the Department of Precision Instruments at Tsinghua University, following the completion of my Bachelor of Engineering (B.Eng) degree in the Department of Automatic Control at Shandong University in 2017.

  My professional journey commenced as an Algorithm Engineer at JD X Research Department, where I immersed myself in cutting-edge projects that laid a strong foundation for my career. Building on that invaluable experience, my current role at Xiaopeng Autonomous Driving Center empowers me to delve deeper into the realms of machine learning, with a primary focus on their applications in the field of autonomous driving.

  These cumulative experiences have not only sharpened my skills but also ignited a profound passion for research and development in these domains. I am wholeheartedly dedicated to pushing the boundaries of knowledge and technology, with the ultimate goal of driving innovation and delivering groundbreaking solutions in the world of autonomous driving.

content:
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Xiaopeng - Autonomous Driving Center, Shanghai
        sub_title: Senior Algorithm Engineer
        caption: September 2022 – Present
        link: https://www.xiaopeng.com/about.html
        quote: > 
          
        description: | # this will include new lines to allow paragraphs
          (1) Responsible for Xiaopeng P5 mass production model prediction module (CNGP)
          
            - Delivered high-priority issues in OTA4, reducing the rate of false deceleration by over 20% and decreasing the takeover rate by over 30%.
            
            - Enriched a simulation test dataset with over 3000 different scenarios, including intersections, roundabouts, and merge scenarios.

          (2) Responsible for Xiaopeng G9 mass production model prediction module (CNGP, HNGP 2.0)

            - Achieved safety takeovers close to 1 per thousand kilometers for HNGP 2.0 and reduced false decelerations to nearly 4 per thousand kilometers.
    
            - Implemented interactive framework for small intersection prediction algorithms, increasing the vehicle's passing capability at small intersections by over 30%.
    
            - Introduced exit prediction and behavior imitation prediction models, resulting in safety takeovers occurring less than 1 per hundred kilometers.

          (3) Responsible for Xiaopeng G9 mass production model prediction module (XNGP 2.0)

            - Implemented features such as lane optimization at unmarked intersections and merge predictions, achieving a vehicle's passing capability comparable to CNGP at 80%.
    
            - Continuously improved algorithms for scenarios including intersections, roundabouts, small intersections, and cruise control in OTA3, addressing algorithm glitches and ensuring successful deployments in Shanghai and Beijing.
    
            - Completed crucial feature enhancements and algorithm glitch fixes in the XNGP 2.0 sprint plan, resulting in a reduction of takeover rates and false deceleration rates by over 20%.

      - layout: right
        title: JD Group - X Research Department, Beijing
        sub_title: Algorithm Engineer
        caption: August 2020 – August 2022
        link: https://neuhub.jd.com/brand/1
        quote: > 
          
        description: | # this will include new lines to allow paragraphs
          (1) Cutting-Edge Algorithm Research
          
            - Published 11 international top-tier/high-level academic papers during my tenure
            
            - Filed 66 invention patents during my tenure, with 7 patents currently granted
            
            - Served as a reviewer for over ten international top-tier conferences/journals (CVPR 2022, ICML 2022, etc.)

          (2) Responsible for the Prediction Trajectory Prediction Module
          
            - Utilized deep learning methods (LSTM) combined with rules to predict the future movement trajectories of obstacles, resulting in the deployment of the ROVER 5.0 model and a 1.5% improvement in the ADE metric for daily simulation tasks.
            
            - Enhanced efficiency by conducting experiments for over 200 models in a short period, reducing training time from 7 days to 8 hours.
            
            - Combined LSTM networks with VectorNet, further improving the ADE metric by 2%.

            
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Tsinghua University
        sub_title: Master's Degree, Instrumentation and Measurement Engineering
        caption: 2017 -- 2020
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          Research Focus: Machine Learning, Deep Learning, Computer Vision

      - layout: top-right
        title: Shandong University
        sub_title: Bachelor's Degree, Measurement and Control Technology and Instruments
        caption: 2013 -- 2017
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          Research Focus: Control Theory and Control Engineering, Robotics
          
  - title: Papers
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Motion planning in complex urban environments: An industrial application on autonomous last‐mile delivery vehicles. Journal of Field Robotics (JFR), 2022. (Corresponding Author, Impact Factor: 8.3, Q1, Top-tier journal in robotics field)
      
      - Lane Keeping Algorithm for Autonomous Driving via Safe Reinforcement Learning. International Conference on Knowledge Science, Engineering and Management (KSEM), 2021. (Corresponding Author, CCF-C conference)
      
      - ODNASSD: An End-to-end Object Detection Neural Architecture Search Space Design. IEEE International Intelligent Transportation Systems Conference (ITSC), 2021. (Corresponding Author, Top conference in autonomous driving field)
      
      - Learning Bilevel Sparse Regularized Neural Network. CAAI International Conference on Artificial Intelligence, 2021. (First Author, Top conference organized by the Chinese Association for Artificial Intelligence)
      
      - MITNet: Multi-intention Trajectory Network for Motion Prediction. IEEE International Conference on Image, Vision and Computing (ICIVC), 2021. (Corresponding Author, Best Paper Award)
      
      - Enhanced-historical average for long-term prediction. IEEE International Conference on Computer, Control and Robotics (ICCCR), 2022. (First Author)
      
      - Constrained policy optimization algorithm for autonomous driving via reinforcement learning. IEEE International Conference on Image, Vision and Computing (ICIVC), 2021. (Corresponding Author)
      
      - Control algorithm of path planning and path tracking for automated valet parking. Journal of Physics: Conference Series, 2022. (Corresponding Author)
      
      - Outdoor real-time RGBD sensor fusion of stereo camera and sparse lidar. Journal of Physics: Conference Series, 2022. (Corresponding Author)
      
      - Vehicle Localization with Surveillance Cameras. IEEE International Conference on Vision, Image and Signal Processing (ICVISP), 2021. (Corresponding Author)
      
      - VPNet: Vision and Planning Network for Robotic Navigation. IEEE International Conference on Image, Vision and Computing (ICIVC), 2021. (Corresponding Author)


  - title: 发明专利
    layout: text
    content: | # this will include new lines to allow paragraphs
      已授权专利：
      
      - CN113119996B，一种轨迹预测方法、装置、电子设备及存储介质
      
      - CN112896191B，轨迹处理方法、装置、电子设备和计算机可读介质
      
      - CN112896191B，轨迹处理方法、装置、电子设备和计算机可读介质
      
      - CN113548052B，无人驾驶车辆换道控制方法和装置 
      
      - CN113978548B，应用于无人车的转向协同控制方法、装置、设备及介质
      
      - CN113561972B，一种避障控制方法、装置、车辆和存储介质
      
      - CN114664098B，一种路权分配方法和装置
      
      已受理专利：
      - CN114581868A，基于模型通道剪枝的图像分析方法和装置

      - CN113780270A，目标检测方法和装置

      - CN114998388A，轨迹预测方法和装置

      - CN114842460A，一种场景文字检测的方法和装置

      - CN114549838A，分割点云数据的方法、装置、设备和计算机可读介质

      - CN114445630A，图像分割及模型训练方法、装置、终端设备及存储介质

      - CN114187589A，一种目标检测方法、装置、设备和存储介质

      - CN114187311A，一种图像语义分割方法、装置、设备及存储介质

      - CN113838113A，三维物体识别方法和装置

      - CN113703453A，确定行驶轨迹的方法、装置、电子设备及存储介质
      
      - CN114936670A，一种交通预测的方法和装置

      - CN114821537A，活动意图预测方法、装置及无人车

      - CN114399107A，一种交通状态感知信息的预测方法及系统

      - CN114386481A，一种车辆感知信息融合方法、装置、设备及存储介质

      - CN114387325A，一种图像特征处理方法和装置

      - CN113947948A，一种车辆通行控制方法和装置

      - CN113808187A，视差图生成方法、装置、电子设备和计算机可读介质

      - CN115272666A，在线点云语义分割方法、装置、存储介质及电子设备

      - CN114371709A，路径规划方法、设备、存储介质及程序产品

      - CN114261400A，一种自动驾驶决策方法、装置、设备和存储介质

      - CN113971727A，一种语义分割模型的训练方法、装置、设备和介质

      - CN114537421A，调整系统故障的方法、装置、设备和计算机可读介质

      - CN114091592A，一种车辆感知信息融合方法、装置、设备及存储介质

      - CN114212104A，车辆控制方法、装置、车辆和存储介质

      - CN113989757A，辅助驾驶方法、装置、电子设备及存储介质

      - CN113807351A，一种场景文字检测方法和装置

      - CN114771570A，自动驾驶车辆的控制方法和装置

      - CN114771555A，自主泊车故障诊断方法、装置和和无人驾驶车辆

      - CN114022663A，目标行为候选框生成方法及装置、电子设备、存储介质

      - CN114663848A，一种基于知识蒸馏的目标检测方法和装置

      - CN114580539A，一种车辆驾驶策略处理方法和装置

      - CN114399791A，一种行人检测方法、装置、设备和介质

      - CN113792655A，一种意图识别方法、装置、电子设备及计算机可读介质

      - CN113780148A，交通标志图像识别模型训练方法和交通标志图像识别方法
      

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
